name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install --upgrade pip
      - run: pip install flake8
      - run: flake8 . || true  # don't fail yet; just show warnings

  build-assets-if-present:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: |
          if [ -f "package.json" ]; then
            npm ci
            npm run build || echo "No build script; skipping"
          else
            echo "No package.json; skipping asset build"
          fi
